### ISSUE TITLE
err about tag on code-3.2

### ISSUE THREAD

**Issue by lvxingzhe** [xianlubird/mydocker#6]
切换到tag code-3.2,按照《自己动手写docker》上3.2小节root权限运行如下命令：
```
# git checkout code-3.2
# go build .
# ./mydocker  run -ti -m 100m stress  --vm-bytes 200m  --vm-keep  -m 1
```
产生如下报错
```
{"level":"error","msg":"fork/exec /proc/self/exe: no such file or directory","time":"2017-08-10T16:20:27+08:00"}
{"level":"warning","msg":"remove cgroup fail cgroup path error stat mydocker-cgroup: no such file or directory","time":"2017-08-10T16:20:27+08:00"}
{"level":"warning","msg":"remove cgroup fail cgroup path error stat mydocker-cgroup: no such file or directory","time":"2017-08-10T16:20:27+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x401342]

goroutine 1 [running]:
panic(0x557520, 0xc42000e0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.Run(0x564201, 0xc420074100, 0x6, 0x8, 0xc42001a390)
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/run.go:26 +0x102
main.glob..func1(0xc420078140, 0x100, 0xc420078140)
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/main_command.go:48 +0x31d
github.com/xianlubird/mydocker/vendor/github.com/urfave/cli.HandleAction(0x5507c0, 0x5939c0, 0xc420078140, 0xc42004e200, 0x0)
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/xianlubird/mydocker/vendor/github.com/urfave/cli.Command.Run(0x57ee39, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x588a83, 0x51, 0x0, ...)
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/vendor/github.com/urfave/cli/command.go:193 +0xb96
github.com/xianlubird/mydocker/vendor/github.com/urfave/cli.(*App).Run(0xc420001860, 0xc42000a0b0, 0xb, 0xb, 0x0, 0x0)
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/vendor/github.com/urfave/cli/app.go:250 +0x812
main.main()
	/home/aimingzhen/gopath/src/github.com/xianlubird/mydocker/main.go:31 +0x153
```
能帮忙解决一下吗？
运行环境如下：
os:  ubuntu14.04 ,linux 3.13.0.83
go:1.7.1

**Comment by chapin666** [comment]
+1 我也遇到了

**Comment by BSWANG** [comment]
不好意思，这个是后来合代码合并的有点问题，需要把这个文件中的 container/container_process.go 这一行注释掉运行

![image](https://user-images.githubusercontent.com/3598874/29169490-e3cc25ee-7e06-11e7-8a74-f83cd5085a79.png)

**Comment by BSWANG** [comment]
新的fix的代码也已经推送上去了。
